changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: "🚀 New Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "📖 Documentation"
      labels:
        - documentation
        - docs
    - title: "🏠 Internal & Maintenance"
      labels:
        - internal
        - chore
        - refactor
    - title: "🧪 Testing"
      labels:
        - testing
        - tests
